services:
  mibig-submission-web:
    image: mibig-submission-web
    build: ./web
    restart: always
    ports:
      - 8991:5000

  mibig-submission-api:
    image: mibig-submission-api
    build: ./api
    restart: always
    ports:
      - 8992:8000

    depends_on:
      mibig-submission-db:
        condition: service_healthy

    volumes:
      - ./api/data:/mibig-submission/api/data

    environment:
      DB_DIALECT: postgres
      DB_HOST: mibig-submission-db
      DB_PASS: changeme

  mibig-submission-db:
    image: postgres
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-u", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

    environment:
      PGUSER: postgres
      POSTGRES_DB: mibig_submission
      POSTGRES_PASSWORD: changeme
